### ISSUE TITLE
[PROGRAMCRASH] Wrath of the Gods crashes with a GPF

### ISSUE THREAD

**Issue by Stupend0usMan** [PluMGMK/vbesvga.drv#129]
**Driver version**
Git commit https://github.com/PluMGMK/vbesvga.drv/commit/91b701178d77e5ca58d017d6920381eac532f88c

**Windows version**
Windows 3.11 (to flip between Standard and Enhanced)

**Windows Operating mode**
Testing in Standard Mode

**Does bug also occur with standard VGA driver?**
Game runs fine in standard VGA. For some reason the character animations are being rendered at random locations in 86box using either Video7 (native or generic SVGA driver) or the GX2. I think this might be a bug in 86box. It appears someone was able to play through this in [DOSBox 0.74](https://www.youtube.com/watch?v=brzB9CFd1Pg) years ago without any issues.

**Have you checked the integrity of the driver files as per instructions in `README.md`?**
Yes

**Type of Machine (Real or Virtual)**
VMWare

**What mode(s) does this issue occur in?**
Any mode/any depth

**Is/are there any mode(s) where this issue does not occur?**
No

**To Reproduce**
1. Launch Wrath of the Gods
2. Click introduction or step into a new game
3. Choose between off or on, or just point and click around the game for a bit

**Expected behavior**
Game should not crash during the introduction or changing scenes.

**Screenshots**

1024x768x8 attempt 1:

<img width="1023" height="768" alt="Image" src="https://github.com/user-attachments/assets/7275dfaa-ceed-400f-8c25-cfca3392ec9f" />

<img width="640" height="350" alt="Image" src="https://github.com/user-attachments/assets/e753424e-39fc-4201-b80c-c4e733c6da57" />

1024x768x8 attempt 2:

<img width="1024" height="767" alt="Image" src="https://github.com/user-attachments/assets/edbab3dc-e0ed-4b0f-8e6f-0f8a66345c06" />

<img width="636" height="319" alt="Image" src="https://github.com/user-attachments/assets/f8685433-bf40-4475-b7bd-e043c84cb655" />

1024x768x8 attempt 3 during the beginning of a new game:

<img width="1024" height="769" alt="Image" src="https://github.com/user-attachments/assets/6c79465d-7a98-43f7-89f0-b528eac37e1f" />

<img width="635" height="369" alt="Image" src="https://github.com/user-attachments/assets/a98a55da-8774-43e7-9fbd-c85ca44852d9" />

1024x768x24 attempt 1:

<img width="641" height="391" alt="Image" src="https://github.com/user-attachments/assets/d63eaf25-5ee3-4ea8-a8fc-bc0460ef8523" />

<img width="1022" height="768" alt="Image" src="https://github.com/user-attachments/assets/a828fd7d-dc2f-47ac-b51a-2dc2fcf2d49e" />

1024x768x24 attempt 2:

<img width="640" height="276" alt="Image" src="https://github.com/user-attachments/assets/1b538c13-580d-44e1-8112-1d79a4900637" />

<img width="1022" height="768" alt="Image" src="https://github.com/user-attachments/assets/5fe8f01d-ccf7-4931-b7e8-a17fce1aee68" />

1024x768x24 attempt 3 during the beginning of a new game:

<img width="636" height="352" alt="Image" src="https://github.com/user-attachments/assets/1b0395f0-1e8b-4d03-be7c-2d5fe8dcfae7" />

<img width="1022" height="769" alt="Image" src="https://github.com/user-attachments/assets/5f5809ca-cbb4-4d11-921d-c1e3967402cc" />

Comparing a scene at `Depth=8` and `Depth=16` or `Depth=24`

<img width="641" height="385" alt="Image" src="https://github.com/user-attachments/assets/a3009b26-952e-46dd-b0f9-18457daa94e1" />

<img width="641" height="385" alt="Image" src="https://github.com/user-attachments/assets/55d4173d-c11e-4aff-8a51-17748ceaecef" />

**Additional context**
It's confusing to describe the GPF that's happening because I seem to be getting a different crash every time, but it always happens at the same point. The introduction causes the GPF to happen before transitioning to the second image through a tiling animation. Sound still plays until the end 😆 . There's times where the GPF doesn't happen in the introduction, but the second image would come out to look like garbage. The images that follow then appear normally. You can see the tiling effect on the linked DOSBox video at [0:30](https://youtu.be/brzB9CFd1Pg?si=1jRTngQEKWK_2lF6&t=30). The other crash always happens if I want to talk to the character in the third attempt screenshots.

Character animations seem to be fine. It appears at `Depth=16` or `Depth=24` the Luminaria introduction and some of the scenes are filling white space around certain images. The game does warn you to suggest playing either in 16 or 256 colors, but on a comparison with the GX2 I did not see the white space issue happening in 16 or 24-bit color.

You can also play the game online [here](https://www.wrathgame.com/)!

**Comment by PluMGMK** [comment]
The randomness and the involvement of `BP` operands in most of the crashes suggests that uninitialized data is being read from the stack, and having slightly different consequences depending on what it is. It always seems to be in segment 8, which is `_DIMAPS` – the same segment is responsible for #113 and a whole slew of others, and is also where I found that issue I [alluded to the other day](https://github.com/PluMGMK/vbesvga.drv/issues/115#issuecomment-3681950123).

So yeah, I think there's a lot of rushed code in that segment, which is probably worth an audit and a polish! (As an aside, that segment confusingly shows up as "`_TEXTSTUFF`" when using the debugging symbols – I realize now that that's because `_TEXTSTUFF` is eighth on the list in `vbesvga.def` but is not actually used anywhere in the code!)

**Comment by PluMGMK** [comment]
More stack faults – could also be resolved by beta2? The involvement of `_DIMAPS` suggests otherwise though…

**Comment by Stupend0usMan** [comment]
The same issues are still currently happening with the latest beta2 build.

**Comment by PluMGMK** [comment]
The problem is somewhere in `RleBlt`. It seems that there's a mismatched push / pop somewhere, resulting in a `RET` to a random location somewhere in one of the subroutines in `RLD.ASM`. Finding it is gonna be painful though…

**Comment by Stupend0usMan** [comment]
That's awesome, the crashes are gone! I don't know if it's just on my end, but I'm still noticing some weird cases in game where certain dialog animations just get skipped entirely and the white filled backgrounds are still being done in high color. Sometimes the animations play, other times they don't. Do we want to have another issue to investigate any further cleanup if it's reproduced?

**Comment by Stupend0usMan** [comment]
I did another run from scratch along with running `VBESVGA` in 86box just to be sure and didn't see the issue with the cutscenes after realizing pressing almost any key can cause them to skip haha. The workaround to the white backgrounds appearing in True Color involves resetting the swapfile as they reappear on the next reboot. I'd say this is good enough!
